export default {
  TOKEN: '$TOKEN',
  MY_REFERRAL_CODE: '$MY_REFERRAL_CODE',
  REFERRAL_CODE: '$REFERRAL_CODE',
  TOKEN_EMAIL_VERIFY_QS: 'token',
  REFERRAL_QUERY: 'referral',
  UNBOXING_QUERY: 'unboxing',
  INTRO_QUERY: 'intro',
  PRODUCT_PRICE: '$PRODUCT_PRICE',
  PAYMENT_INFORMATION: '$PAYMENT_INFORMATION',
  CART_INFORMATION: '$CART_INFORMATION',
  COIN_FIAT_RATE: '$COIN_FIAT_RATE'
};
